train:
  batch_size: 16
<<<<<<< HEAD
=======
  init_lr: 0.001
<<<<<<< HEAD
>>>>>>> origin/develop
  max_epochs: 2
=======
  max_epochs: 4
>>>>>>> origin/develop
  val_split: 0.2
  nb_workers: 0 # set to 0 if you get an error

evaluate:
  batch_size: 1
  nb_workers: 0 # set to 0 if you get an error

audio:
  audio_duration: 30000
  sample_rate: 44100
  nb_channels: 2
  time_shift: 0.2 # in percentage of audio_duration
