name: deploy-services-workflow

on:
  push:
    branches:
      - feature_devops-whisper

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Run python script
        run: |
          python3 --version

